
# Niboo addons: copy from existing install

# - name: Ensure Niboo's Odoo addons are present and up to date
#   git:
#     dest: "{{ odoo_niboo_addons_path }}"
#     repo: https://{{ odoo_niboo_addons_gitlab_token_username }}:{{ odoo_niboo_addons_gitlab_token_secret }}@{{ odoo_niboo_addons_repo_address }}
#     # version: "main"
#     # update: no
#     update: yes
#     clone: yes
#   ignore_errors: yes
#   become: yes
#   tags: odoo_install,odoo_git,odoo_niboo_addons

- name: "Copy SSH public key of {{ odoo_niboo_addons_source_host }}"
  delegate_to: "{{ odoo_niboo_addons_source_host }}"
  slurp:
      src: /root/.ssh/id_ed25519.pub # required. The file on the remote system to fetch. This I(must) be a file, not a directory.
  register: odoo_niboo_addons_source_publickey
  when: odoo_niboo_addons_rsync
  tags:
  - odoo_niboo_addons
  - odoo_niboo_addons_rsync

- name: Authorize key from {{ odoo_niboo_addons_source_host }} to current Odoo instance {{ ansible_host }}"
  authorized_key:
  # FIXME: Don't use root for that
      user: root
      key: "{{ odoo_niboo_addons_source_publickey.content | b64decode  }}"
  when: odoo_niboo_addons_rsync
  tags:
  - odoo_niboo_addons
  - odoo_niboo_addons_rsync


- name: "Copy Niboo's Odoo addons files at {{ odoo_niboo_addons_path }} from {{ odoo_niboo_addons_source_host }}"
# Slash in source is important to avoid a dir to be created inside
  command: "rsync -a --delete --partial --stats -e 'ssh -o StrictHostKeyChecking=no' {{ odoo_niboo_addons_source_path }}/ {{ ansible_host }}:{{ odoo_niboo_addons_path }}/"
  register: niboo_addons_rsync_output
  delegate_to: "{{ odoo_niboo_addons_source_host }}"
  become: yes
  when:
    - odoo_niboo_addons_rsync
    - not ansible_check_mode
  tags:
  - odoo_niboo_addons
  - odoo_niboo_addons_rsync
  notify: Restart Odoo

- name: Ensure Niboo's 3 Odoo addons subfolders are present 1/2
  stat:
    path: "{{ odoo_niboo_addons_path }}/{{ item }}"
  register: odoo_niboo_addons_check
  with_items:
  - niboo-internal
  - niboo-community
  - paid-community
  tags: odoo_niboo_addons

- name: Ensure Niboo's 3 Odoo addons subfolders are present 2/2
  ansible.builtin.debug:
    msg: "Niboo's Odoo addons subfolders exist (cannot verify content)"
  when:
    - item is defined
    - not ansible_check_mode
  failed_when: not item.stat.exists or not item.stat.isdir
  # failed_when: item.stat.isdir is defined and not item.stat.isdir
  loop: "{{ odoo_niboo_addons_check.results }}"
  tags: odoo_niboo_addons
