# Not tested yet
# - import_playbook: odoo_enablemaintenance.yml
# TODO: Add "listen" and carefully restart/recreate by checking stuff before

# - name: Recreate Odoo
#   docker_compose:
#     recreate: always
#     state: present
#     timeout: 600
#     project_src: "{{ odoo_project_path }}"
#   environment: 
#     ODOO_ENV_VERSION: "{{ odoo_registry_image_version }}"
#   become: yes

# - name: Restart Odoo
#   docker_compose:
#     restarted: yes
#     timeout: 600
#     state: present
#     project_src: "{{ odoo_project_path }}"
#   become: yes
  # environment: 
  #   ODOO_ENV_VERSION: "{{ odoo_registry_image_version }}"
# - import_playbook: odoo_disablemaintenance.yml
