# Not tested yet
# - import_playbook: odoo_enablemaintenance.yml
# TODO: Add "listen" and carefully restart/recreate by checking stuff before

# - name: Recreate Odoo
#   docker_compose:
#     recreate: always
#     state: present
#     timeout: 600
#     project_src: "{{ odoo_project_path }}"
#   become: yes

# - name: Restart Odoo
#   docker_compose:
#     restarted: yes
#     timeout: 600
#     state: present
#     project_src: "{{ odoo_project_path }}"
#   become: yes
# - import_playbook: odoo_disablemaintenance.yml
