
- name: Recreate Odoo
  docker_compose:
    recreate: always
    state: present
    timeout: 60
    debug: yes
    project_src: "{{ odoo_project_path }}"
    remove_orphans: yes
  become: yes
  environment:
  - COMPOSE_HTTP_TIMEOUT=600
  - DOCKER_CLIENT_TIMEOUT=600
  
- name: Restart Odoo
  docker_compose:
    restarted: yes
    # only if definition changed (default)
    recreate: smart
    timeout: 60
    debug: yes
    state: present
    project_src: "{{ odoo_project_path }}"
    remove_orphans: yes
  environment:
  - COMPOSE_HTTP_TIMEOUT=600
  - DOCKER_CLIENT_TIMEOUT=600
  become: yes